package com.lipy.step.dao.core;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pedometerEntityDaoConfig;
    private final DaoConfig calendarEntityDaoConfig;

    private final PedometerEntityDao pedometerEntityDao;
    private final CalendarEntityDao calendarEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pedometerEntityDaoConfig = daoConfigMap.get(PedometerEntityDao.class).clone();
        pedometerEntityDaoConfig.initIdentityScope(type);

        calendarEntityDaoConfig = daoConfigMap.get(CalendarEntityDao.class).clone();
        calendarEntityDaoConfig.initIdentityScope(type);

        pedometerEntityDao = new PedometerEntityDao(pedometerEntityDaoConfig, this);
        calendarEntityDao = new CalendarEntityDao(calendarEntityDaoConfig, this);

        registerDao(PedometerEntity.class, pedometerEntityDao);
        registerDao(CalendarEntity.class, calendarEntityDao);
    }
    
    public void clear() {
        pedometerEntityDaoConfig.getIdentityScope().clear();
        calendarEntityDaoConfig.getIdentityScope().clear();
    }

    public PedometerEntityDao getPedometerEntityDao() {
        return pedometerEntityDao;
    }

    public CalendarEntityDao getCalendarEntityDao() {
        return calendarEntityDao;
    }

}
