package com.lipy.step.dao.core;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "PedometerLog".
*/
public class PedometerEntityDao extends AbstractDao<PedometerEntity, Long> {

    public static final String TABLENAME = "PedometerLog";

    /**
     * Properties of entity PedometerEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Date = new Property(1, String.class, "date", false, "DATE");
        public final static Property StepCount = new Property(2, Integer.class, "stepCount", false, "STEP_COUNT");
        public final static Property DistanceInMeters = new Property(3, Double.class, "distanceInMeters", false, "DISTANCE_IN_METERS");
        public final static Property Status = new Property(4, Integer.class, "status", false, "STATUS");
        public final static Property TargetStepCount = new Property(5, Integer.class, "targetStepCount", false, "TARGET_STEP_COUNT");
    };


    public PedometerEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PedometerEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PedometerLog\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DATE\" TEXT NOT NULL UNIQUE ," + // 1: date
                "\"STEP_COUNT\" INTEGER," + // 2: stepCount
                "\"DISTANCE_IN_METERS\" REAL," + // 3: distanceInMeters
                "\"STATUS\" INTEGER," + // 4: status
                "\"TARGET_STEP_COUNT\" INTEGER);"); // 5: targetStepCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PedometerLog\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PedometerEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDate());
 
        Integer stepCount = entity.getStepCount();
        if (stepCount != null) {
            stmt.bindLong(3, stepCount);
        }
 
        Double distanceInMeters = entity.getDistanceInMeters();
        if (distanceInMeters != null) {
            stmt.bindDouble(4, distanceInMeters);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(5, status);
        }
 
        Integer targetStepCount = entity.getTargetStepCount();
        if (targetStepCount != null) {
            stmt.bindLong(6, targetStepCount);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PedometerEntity readEntity(Cursor cursor, int offset) {
        PedometerEntity entity = new PedometerEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // date
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // stepCount
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // distanceInMeters
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // status
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // targetStepCount
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PedometerEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDate(cursor.getString(offset + 1));
        entity.setStepCount(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setDistanceInMeters(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setStatus(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setTargetStepCount(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PedometerEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PedometerEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
