package com.lipy.step.dao.core;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PedometerLog".
 */
public class PedometerEntity {

    private Long id;
    /** Not-null value. */
    private String date;
    private Integer stepCount;
    private Integer status;
    private Integer targetStepCount;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PedometerEntity() {
    }

    public PedometerEntity(Long id) {
        this.id = id;
    }

    public PedometerEntity(Long id, String date, Integer stepCount, Integer status, Integer targetStepCount) {
        this.id = id;
        this.date = date;
        this.stepCount = stepCount;
        this.status = status;
        this.targetStepCount = targetStepCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Integer getStepCount() {
        return stepCount;
    }

    public void setStepCount(Integer stepCount) {
        this.stepCount = stepCount;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getTargetStepCount() {
        return targetStepCount;
    }

    public void setTargetStepCount(Integer targetStepCount) {
        this.targetStepCount = targetStepCount;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
