package com.lipy.step.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table "PedometerLog".
 */
public class PedometerEntity implements Serializable{

    private Long id;
    /** Not-null value. */
    private String date;
    private Integer dailyStep;
    private Integer totalSteps;
    private Integer tagStep;
    private Integer lastSystemSteps;
    private Boolean reStart;
    private Boolean punchCard;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PedometerEntity() {
    }

    public PedometerEntity(Long id) {
        this.id = id;
    }

    public PedometerEntity(Long id, String date, Integer dailyStep, Integer totalSteps, Integer tagStep, Integer lastSystemSteps, Boolean reStart, Boolean punchCard) {
        this.id = id;
        this.date = date;
        this.dailyStep = dailyStep;
        this.totalSteps = totalSteps;
        this.tagStep = tagStep;
        this.lastSystemSteps = lastSystemSteps;
        this.reStart = reStart;
        this.punchCard = punchCard;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Integer getDailyStep() {
        return dailyStep;
    }

    public void setDailyStep(Integer dailyStep) {
        this.dailyStep = dailyStep;
    }

    public Integer getTotalSteps() {
        return totalSteps;
    }

    public void setTotalSteps(Integer totalSteps) {
        this.totalSteps = totalSteps;
    }

    public Integer getTagStep() {
        return tagStep;
    }

    public void setTagStep(Integer tagStep) {
        this.tagStep = tagStep;
    }

    public Integer getLastSystemSteps() {
        return lastSystemSteps;
    }

    public void setLastSystemSteps(Integer lastSystemSteps) {
        this.lastSystemSteps = lastSystemSteps;
    }

    public Boolean getReStart() {
        return reStart;
    }

    public void setReStart(Boolean reStart) {
        this.reStart = reStart;
    }

    public Boolean getPunchCard() {
        return punchCard;
    }

    public void setPunchCard(Boolean punchCard) {
        this.punchCard = punchCard;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
