package com.lipy.step.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table "PedometerLog".
 */
public class PedometerEntity implements Serializable{

    private Long id;
    /** Not-null value. */
    private String date;
    private Integer dailyStep;
    private Integer status;
    private Integer totalSteps;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PedometerEntity() {
    }

    public PedometerEntity(Long id) {
        this.id = id;
    }

    public PedometerEntity(Long id, String date, Integer dailyStep,Integer totalSteps, Integer status) {
        this.id = id;
        this.date = date;
        this.dailyStep = dailyStep;
        this.status = status;
        this.totalSteps = totalSteps;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public Integer getDailyStep() {
        return dailyStep;
    }

    public void setDailyStep(Integer dailyStep) {
        this.dailyStep = dailyStep;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getTotalSteps() {
        return totalSteps;
    }

    public void setTotalSteps(Integer totalSteps) {
        this.totalSteps = totalSteps;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
